name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - asn1crypto=1.0.1=py36_0
  - attrs=19.3.0=py_0
  - audioread=2.1.8=py36h9f0ad1d_2
  - backcall=0.1.0=py36_0
  - beautifulsoup4=4.8.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - boost-cpp=1.72.0=h0caebb8_0
  - boto=2.49.0=py36_0
  - boto3=1.9.234=py_0
  - botocore=1.12.234=py_0
  - bz2file=0.98=py36_1
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - certifi=2020.4.5.2=py36h9f0ad1d_0
  - cffi=1.12.3=py36h7a1dbc1_0
  - chardet=3.0.4=py36_1003
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.1=py36_0
  - cryptography=2.7=py36h7a1dbc1_0
  - cryptography-vectors=2.7=py_0
  - curl=7.68.0=h4496350_0
  - cycler=0.10.0=py36h009560c_0
  - cython=0.29.13=py36ha925a31_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - docutils=0.15.2=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.9=he025d50_2
  - ffmpeg=4.2.3=ha925a31_0
  - fiona=1.8.4=py36h0d92105_1001
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hd288d7e_1002
  - gdal=2.3.3=py36hdf43c64_0
  - gensim=3.8.0=py36hf9181ef_0
  - geographiclib=1.50=py_0
  - geopandas=0.6.3=py_0
  - geopy=1.22.0=pyh9f0ad1d_0
  - geos=3.7.1=h33f27b4_0
  - h5py=2.9.0=py36h5e291fa_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py36_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.0=py_0
  - jsonschema=3.0.2=py36_0
  - jupyter_client=5.3.3=py36_1
  - jupyter_core=4.5.0=py_0
  - jupyterlab=2.1.2=py_0
  - jupyterlab_server=1.1.3=py_0
  - kealib=1.4.7=h07cbb95_6
  - kiwisolver=1.1.0=py36ha925a31_0
  - krb5=1.16.4=hc04afaa_0
  - libcurl=7.68.0=h4496350_0
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.5=hb0bdaea_2
  - librosa=0.6.1=py36_0
  - libsodium=1.0.16=h9d3ae62_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h6a0152f_1026
  - libssh2=1.9.0=h3235a2c_2
  - libtiff=4.0.9=hf1753bf_1
  - libxgboost=0.90=0
  - libxml2=2.9.10=h5d81f1c_1
  - llvmlite=0.32.1=py36h9f0ad1d_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.1.1=py36hc8f65d3_0
  - matplotlib-base=3.2.1=py36hf0cddfc_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.14=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.6.0=py36_1
  - nbformat=4.4.0=py36h3a5bc1b_0
  - networkx=2.3=py_0
  - nltk=3.4.5=py36_0
  - notebook=6.0.1=py36_0
  - numba=0.49.1=py36hcc50265_0
  - numpy=1.16.5=py36h19fb1c0_0
  - numpy-base=1.16.5=py36hc3f5095_0
  - openssl=1.1.1g=he774522_0
  - pandas=0.25.1=py36ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.44=h6538335_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.2.3=py36_0
  - plotly=4.1.1=py_0
  - proj4=5.2.0=h6538335_1006
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - py-xgboost=0.90=py36_0
  - py4j=0.10.7=py36_0
  - pycparser=2.19=py36_0
  - pydotplus=2.0.2=py36_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.6=py36hfa6e2cd_1002
  - pyqt=5.9.2=py36h6538335_2
  - pyreadline=2.1=py36_1
  - pyrsistent=0.15.4=py36he774522_0
  - pysocks=1.7.1=py36_0
  - pyspark=2.4.4=py_0
  - python=3.6.9=h5500b2f_0
  - python-dateutil=2.8.0=py36_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pywin32=223=py36hfa6e2cd_1
  - pywinpty=0.5.5=py36_1000
  - pyzmq=18.1.0=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.22.0=py36_0
  - resampy=0.2.2=py_0
  - retrying=1.3.3=py36_2
  - rtree=0.9.4=py36h9a6d676_1
  - s3transfer=0.2.1=py36_0
  - scikit-learn=0.21.3=py36h6288b17_0
  - scipy=1.3.1=py36h29ff71c_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.4.0=py36_0
  - shapely=1.6.4=py36h7d20962_1005
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.12.0=py36_0
  - smart_open=1.8.4=py_0
  - soupsieve=1.9.3=py36_0
  - sqlite=3.30.0=he774522_0
  - statsmodels=0.10.1=py36h8c2d366_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py36he774522_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py36_0
  - urllib3=1.24.2=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.6=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xerces-c=3.2.3=ha925a31_1
  - xlrd=1.2.0=py36_0
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
prefix: C:\Users\jaker\anaconda3\envs\learn-env

